- hosts: masters
  become: yes
  tags: cluster
  roles:
    - { role: node-master} 
     
- hosts: workers
  tags: cluster
  become: yes
  roles:
    - { role: node-worker} 
    
#- hosts: masters
#  become: yes
#  roles:
#    - { role: grafana}
#  collections:
#  - kubernetes.core


- hosts: masters
  tags: monitoring
  become: yes
  roles:
    - { role: monitoring/metrics-server} 


- hosts: workers
  tags: cicd
  become: yes
  roles:
    - { role: cicd/jenkins-worker} 

- hosts: masters
  tags: cicd
  become: yes
  roles:
    - { role: cicd/jenkins-master} 
