- hosts: masters
  become: yes
  tags: cluster
  roles:
    - node-master
     
- hosts: workers
  tags: cluster
  become: yes
  roles:
    - node-worker 
    
#- hosts: masters
#  become: yes
#  roles:
#    - { role: grafana}
#  collections:
#  - kubernetes.core


- hosts: masters
  tags: monitoring
  become: yes
  roles:
    - monitoring/metrics-server


- hosts: workers
  tags: cicd
  become: yes
  roles:
    - cicd/jenkins-worker 

- hosts: masters
  tags: cicd
  become: yes
  roles:
    - cicd/jenkins-master
    
- hosts: nfs-server
  become: yes
  tags: nfs-server
  roles:
    - storage/nfs-server 
  vars:
    nfs_server_exports:
    - export:
      access:
        - hostname: '*'
          options:
            - 'rw'
            - 'sync'
            - 'no_subtree_check'
            - 'no_root_squash'
      mode: "u=rwx,g=rwx,o=rwx"
      path: '/data/'
      
- hosts: masters
  tags: nfs-server
  become: yes
  roles:
    - storage/nfs-provisionner  
     
