- name: Add nfs-subdir-external-provisioner Helm Repo
  tags: metric
  become: false
  command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: Install nfs-subdir-external-provisioner Helm Chart
  tags: metric
  become: false
  command: helm install nfs-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server=192.168.56.15 --set nfs.path=/data    
 
